name: Deploy with AWS access keys (debug)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (access keys)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Check env vars existence (no secret values printed)
        shell: bash
        run: |
          echo "== Check AWS env vars set =="
          if [ -z "${AWS_ACCESS_KEY_ID:-}" ]; then
            echo "ERROR: AWS_ACCESS_KEY_ID is NOT set"
            exit 1
          else
            echo "OK: AWS_ACCESS_KEY_ID is set"
          fi
          if [ -z "${AWS_SECRET_ACCESS_KEY:-}" ]; then
            echo "ERROR: AWS_SECRET_ACCESS_KEY is NOT set"
            exit 1
          else
            echo "OK: AWS_SECRET_ACCESS_KEY is set"
          fi
          echo "AWS_REGION=${AWS_REGION:-<not set>}"  # region value printed (safe)
      - name: Verify caller identity
        run: |
          aws sts get-caller-identity
      - name: Try S3 list (may fail if user lacks S3 perms)
        run: |
          aws s3 ls || true
